spring:
  application:
    name: auth-server
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/auth?characterEncoding=utf8&generateSimpleParameterMetadata=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 10
    host: ${REDIS_HOST:10.2.1.70}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: 20

server:
  port: 6001

jwt:
  rsa-secret: 1112dda
client:
  rsa-secret: 1112dda



management:
  endpoint:
    health:
      enabled: true
